name: Build and Validate

on:
  push:
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1  # v4

      - name: Build and validate multi-arch image
        run: make build-validate

      - name: Display build info
        run: make log

      - name: Upload CI files to artifacts (on failure)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7
        if: failure()
        with:
          name: ci-artifacts
          path: 'ci'
          retention-days: 7
