name: Build and Validate

on:
  push:
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130  # v3

      - name: Build and validate multi-arch image
        run: make build-validate

      - name: Display build info
        run: make log

      - name: Upload CI files to artifacts (on failure)
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4
        if: failure()
        with:
          name: ci-artifacts
          path: 'ci'
          retention-days: 7
